  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: "val/acc_token"      
    patience: 10             
    min_delta: 0.0001 
    mode: "max"             
    verbose: True           