  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: "val/acc_token"      
    patience: 8             
    min_delta: 0.01 
    mode: "max"             
    verbose: True           