#!/bin/bash

# Usage: bash launch_job.sh <LANGUAGE> [--prepare|--rest] [MIN_TRAIN_LENGTH] [MAX_TRAIN_LENGTH] [MIN_VAL_LENGTH] [MAX_VAL_LENGTH] [MIN_TEST_LENGTH] [MAX_TEST_LENGTH] 

LANGUAGE=$1
FLAG=$2
MIN_TRAIN_LENGTH=${3:-20}
MAX_TRAIN_LENGTH=${4:-20}
MIN_VAL_LENGTH=${5:-20}
MAX_VAL_LENGTH=${6:-20}
MIN_TEST_LENGTH=${7:-20}
MAX_TEST_LENGTH=${8:-20}
# Set model lengths based on language and max train length
if [ "$LANGUAGE" = "arithmetic" ]; then
    SHORT_MODEL_LENGTH=128
    LONG_MODEL_LENGTH=256
elif [ "$LANGUAGE" = "bfvp" ]; then
    SHORT_MODEL_LENGTH=128
    LONG_MODEL_LENGTH=256
else
    SHORT_MODEL_LENGTH=$(( MAX_TRAIN_LENGTH * 3 / 2 ))
    LONG_MODEL_LENGTH=$(( MAX_TRAIN_LENGTH * 3 ))
fi

# sbatch scripts/train_classifier.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $SHORT_MODEL_LENGTH

if [ "$FLAG" = "--prepare" ]; then
    sbatch scripts/train_classifier.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $SHORT_MODEL_LENGTH
    sbatch scripts/train_empty_padding.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $LONG_MODEL_LENGTH
    sbatch scripts/train_cot.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $LONG_MODEL_LENGTH
elif [ "$FLAG" = "--rest" ]; then
    sbatch scripts/train_empty_padded_looping.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $LONG_MODEL_LENGTH
    sbatch scripts/train_looping.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $SHORT_MODEL_LENGTH
    sbatch scripts/train_mdm.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $LONG_MODEL_LENGTH
    sbatch scripts/train_padded_looping.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $LONG_MODEL_LENGTH
    sbatch scripts/train_padding.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $LONG_MODEL_LENGTH
else
    sbatch scripts/train_classifier.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $SHORT_MODEL_LENGTH
    sbatch scripts/train_cot.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $LONG_MODEL_LENGTH
    sbatch scripts/train_empty_padded_looping.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $LONG_MODEL_LENGTH
    sbatch scripts/train_empty_padding.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $LONG_MODEL_LENGTH
    sbatch scripts/train_looping.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $SHORT_MODEL_LENGTH
    sbatch scripts/train_mdm.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $LONG_MODEL_LENGTH
    sbatch scripts/train_padded_looping.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $LONG_MODEL_LENGTH
    sbatch scripts/train_padding.sh $LANGUAGE $MIN_TRAIN_LENGTH $MAX_TRAIN_LENGTH $MIN_VAL_LENGTH $MAX_VAL_LENGTH $MIN_TEST_LENGTH $MAX_TEST_LENGTH $LONG_MODEL_LENGTH
fi

